# WARNING: This file is generated by the bump.sh script. Do not edit it manually.
{
  nixpkgs = {
    branch = "nixpkgs-unstable";
    commit = "929116e316068c7318c54eb4d827f7d9756d5e9c";
    commit_date = "2024-12-05T05:26:01+00:00";
    source_url = "https://github.com/NixOS/nixpkgs/archive/929116e316068c7318c54eb4d827f7d9756d5e9c.tar.gz";
    hash = {
      nix32 = {
        packed = {
          comment = "nix-prefetch-url generated hash of the nix archive file obtained from github archive (packed)";
          sha256 = "0g14wk0l0aihrl5rw4qcdqy6szpk2h39rf4bxsz7mk8kaz1nabqb";
          sha512 = "303wibr5hn8zazi3izvjkinipmw4nmrbiyacv66k62kx1i64fv2k4jkiq64zkfkl3mmxjl9n7kaf9q9264b7q0xnps91wmvzlc1s1li";
        };
        unpacked = {
          comment = "nix-prefetch-url generated hash of the nix archive file obtained from github archive (unpacked)";
          sha256 = "1am61kcakn9j47435k4cgsarvypb8klv4avszxza0jn362hp3ck8";
        };
      };
      tar = {
        comment = "openssl generated hashes of the actual tar.gz file obtained from github archive";
        sha256 = "0b2f65c35713cd7abeee8bb89c0614f37e6d3c6e0c139e0bcd302a40c1e4243c";
        sha384 = "60840258c34cd61fc0d78c3a9ed282ff1d6982bae87b9078779d985862a4a005a028783cd1d7d8857c0111d648ff692f";
        sha512 = "91061d18fdbbf290f4b51de0b388110927a7e6b189ca5eeba0d3cd4f0c8e539229b62326863e8599c66ca67c5cb95ac2eb8d364eb97f1cf1ab8f2c2c79453ec0";
        sha3_256 = "b9c1d5d2d42f7e75c0a76b71710667420d2fa6784aee3787857a7dbe981b37b4";
        sha3_384 = "dbb50f748c2c7c87fb5593a0c44702e60f398ef93e101d8b35b14c01406f71e8452f57cc6b79e43c7c929e904c7a3fd2";
        sha3_512 = "648d7d3ac0cbf2f7205ede4d4a6264427f1c5a9a2c1eee2d7ad10a1168a140faa119d6646ef30c34cfde0385c4d4cd57b9c35ccb1db94ca2eb2faee4d918c667";
        blake2b512 = "0f8d823616dd938c6954d59c52ab4b8f96b98e8eb82f4a3e96cbd6be31022c5752557ed33500f05a6ac200f97d2645cee5ee79068678d883ba34977e40d311bb";
        blake2s256 = "d1560ff28f90bc05b923308e44e54280754f384b9ea564763cb18004fed1dc5e";
      };
    };
  };
  rust = {
    stable = {
      channel = "stable";
      version = "1.83.0";
      llvm = "19";
      profile = "default";
      targets = [
        "x86_64-unknown-linux-gnu"
        "x86_64-unknown-linux-musl"
      ];
      extensions = [
        "cargo"
        "clippy"
        "rust-std"
      ];
    };
  };
}
