# WARNING: This file is generated by the bump.sh script. Do not edit it manually.
{
  nixpkgs = {
    branch = "nixpkgs-unstable";
    commit = "02f2cb8e0feb4596d20cc52fda73ccee960e3538";
    commit_date = "2025-10-24T23:52:36+00:00";
    source_url = "https://github.com/NixOS/nixpkgs/archive/02f2cb8e0feb4596d20cc52fda73ccee960e3538.tar.gz";
    hash = {
      nix32 = {
        packed = {
          comment = "nix-prefetch-url generated hash of the nix archive file obtained from github archive (packed)";
          sha256 = "1pqnrgyhv613ym8ps2z48bsazzdx4whja5khj6gllz31494ymf4p";
          sha512 = "1pc2hlkdfrvnd9c0dgwnkwsv77jwnj666fr168jgqxfrazsinw13zxnrncg12sjszwcqhimz0x5gnszrm6kz5v86idsrb8mhcvkah17";
        };
        unpacked = {
          comment = "nix-prefetch-url generated hash of the nix archive file obtained from github archive (unpacked)";
          sha256 = "0k4za9vmdxpz5jixspyz2ypc25ymcxijpssgwaacz6l9fcgg0zdl";
        };
      };
      tar = {
        comment = "openssl generated hashes of the actual tar.gz file obtained from github archive";
        sha256 = "97b8ea4922617c4a9f917016252127bdfdaff442e40b7d51f523980dfdcb16df";
        sha384 = "a906aa41ebd42479ad5adb95b2d53a31dfe83d0548ea098845d032ed9c4b35275e67746806d0bac7c5386b441089ebfd";
        sha512 = "274035378315adac5b3468973f4dcd5fdb573af83542ccf8d7528bf098cdb6ff11b88dfaabec3a7e1299909d31465a2ecfd99a4fcb5f032c35bbb36b9342c16e";
        sha3_256 = "041be60f5028c26a6f974048b9a0e3edda3827ca53e39278a209aec3f52ee4ac";
        sha3_384 = "0a549629ab469a684ddcc2b7dd60b5e1933b70d2ac7454bcdd9bcb1f6e6557213ea6b77ba4196de2e5be3b79a6230dde";
        sha3_512 = "d792ca42703de795aa8708b2a7d014a78dcfe53734a91244267b834b8dc1061922100b7a67b1b3bb3b1d6de25e138617ad60f58ef79e7a19ef92457062c07689";
        blake2b512 = "999ecd09517b18dee7f947db0a0660bb4c9ff961e8cc8713d5c38b6f65e4785fb460c72360d2ae9fcb685b9799d776ec1094afafbdabd36be4cd0a8d53d89a68";
        blake2s256 = "549ebb959a685bed4e2d64ddd7079ca590d83815e0dbcb7d43895cf5baf59b6a";
      };
    };
  };
  rust = {
    stable = {
      channel = "stable";
      toolchain_toml_hash = "sha256-SJwZ8g0zF2WrKDVmHrVG3pD2RGoQeo24MEXnNx5FyuI=";
      version = "1.90.0";
      llvm = "20";
      profile = "default";
      targets = [
        "x86_64-unknown-linux-gnu"
      ];
      extensions = [
        "cargo"
        "clippy"
        "llvm-bitcode-linker"
        "llvm-tools"
        "rust-analyzer"
        "rust-docs"
        "rust-src"
        "rust-std"
        "rustc"
        "rustfmt"
      ];
    };
  };
  dplane-rpc = {
    branch = "master";
    rev = "e8fc33db10e1d00785f2a2b90cbadcad7900f200";
    hash = "sha256-tjN4qSbKrWfosOV3wt2AnQxmVL0BPZYBjAHG3X00+aM=";
    commit_date = "2025-07-22T12:35:11+00:00";
  };
  dplane-plugin = {
    branch = "master";
    rev = "18a20beb449cc4205c25267c3d6c5b5d40dd0ca0";
    hash = "sha256-FBTUIPGHA2QejCy6ANKAt7JsbnGnb/Wtx74RPuW3uk4=";
    commit_date = "2025-08-07T18:58:02+00:00";
  };
  frr = {
    branch = "hh-master-10.4";
    rev = "489487319b350f9c5f8b8528cf01c336aaa47ad5";
    hash = "sha256-81A98AgfgT5WVa8Imo5wf4/GLO5vGuFSf3+3f93f/fk=";
    commit_date = "2025-09-19T02:29:56+00:00";
  };
  frr-agent = {
    branch = "master";
    rev = "5ae5e297e7b79f33d980f47bd74538af5e50835d";
    hash = "sha256-y2P6DWkXqfyrWO4rcs//5JaciUksn+fPqtQP7tsm4+M=";
    commit_date = "2025-09-03T15:47:57+00:00";
  };
  perftest = {
    branch = "master";
    rev = "799923feb5e9de90c799a86246a4694d9e2d76cc";
    hash = "sha256-iA6UIpCoHFD9i+Te1gCj0DIGgNyX61WYjXQ9b88NG3o=";
    commit_date = "2025-10-22T06:42:45+00:00";
  };
}
