# WARNING: This file is generated by the bump.sh script. Do not edit it manually.
{
  nixpkgs = {
    branch = "nixpkgs-unstable";
    commit = "fa35a3c8e17a3de613240fea68f876e5b4896aec";
    commit_date = "2025-02-08T12:54:32+00:00";
    source_url = "https://github.com/NixOS/nixpkgs/archive/fa35a3c8e17a3de613240fea68f876e5b4896aec.tar.gz";
    hash = {
      nix32 = {
        packed = {
          comment = "nix-prefetch-url generated hash of the nix archive file obtained from github archive (packed)";
          sha256 = "15sg9kyri4sac9vq74fwqrqj0rknsrssw3dvizmnjm4jvb956yjb";
          sha512 = "18pmp4p9wh8iwvc93xb5wf34canfwk0wn7hd9n4z0xgpb54c64hlvyr0a5h66wjr2adjjzda3wggyf78birpspy1b1lc7jzfk38z3sv";
        };
        unpacked = {
          comment = "nix-prefetch-url generated hash of the nix archive file obtained from github archive (unpacked)";
          sha256 = "1kzyyb467zfdkpjmqlys5nncmmhdzz097z9n1ydq18fgmjhvnnzc";
        };
      };
      tar = {
        comment = "openssl generated hashes of the actual tar.gz file obtained from github archive";
        sha256 = "4b7a53d2da925469eb8fbb0dae75d676662071c6dc918377624a9398fd4c4f97";
        sha384 = "bf1ed713611873780d19150fc2902258715da2e3d754a58c3894b361c0e6386ae69ae4726cd060d954a5966d6720d084";
        sha512 = "5b8f8fc6745f1e46c30afeea9be342c7f9f7f850ed4bd994c8921b038b02d96f0a8961a4acfb3af8c4a6068fe56072671523c3f1b2fa486cf388204f97dc7a51";
        sha3_256 = "6f8e642c0139e8bad5faf4ba1ce01885458665ad8fdf4ae73c5a79555f5948b8";
        sha3_384 = "f0bc6c19cc66270b4e9dcd02830da9f2dd5915167d2d322aa5e753fa928043a95c527116fa4d1b33aed45294067837f0";
        sha3_512 = "d7e10c54cc23a71e3afb5bb6af458983460de7e985b81c23b7d5b16311be69e2fa286c5a41ae74a437e3c9acf54e2f7d15907ded147914ef741dfeea04d1f760";
        blake2b512 = "439cc20d802f9ad80e4aadd5740cea6466d840ca664f04c111c602ef878114430c058b17148286f4eae6651d84a40854558eb62b55ceda4bf770fc75081355ac";
        blake2s256 = "31a482b4352c56f2a1a8276ff6e50c8d99aed3b08233ec2848400c0659171753";
      };
    };
  };
  rust = {
    stable = {
      channel = "stable";
      version = "1.84.1";
      llvm = "19";
      profile = "default";
      targets = [
        "x86_64-unknown-linux-gnu"
        "x86_64-unknown-linux-musl"
      ];
      extensions = [
        "cargo"
        "clippy"
        "rust-std"
      ];
    };
  };
}
