version: 2

updates:
  - package-ecosystem: "github-actions"
    target-branch: "main"
    commit-message:
      prefix: "bump(github-actions):"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    labels:
      - "automated"
      - "dependencies"
