ARG IMAGE="ghcr.io/githedgehog/dpdk-sys/dev-env"
ARG TAG="latest"
FROM ${IMAGE}:${TAG} AS dev-env

SHELL ["/bin/bash", "-euxo", "pipefail", "-c"]

# I can't properly set permissions in nix because of the way it works.
# So I have to do this hacky thing to get sudo to work.
RUN chmod 777 /tmp \
 && chmod 4755 /sbin/sudo

ENV SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt

RUN rm /bin/ldconfig
RUN mkdir -p /home/runner
RUN chown -R runner:runner /home/runner
USER runner
CMD ["/bin/bash", "--login"]
