params:
  llvm: &llvm
    - "18"
    - "19"
  rust:
    - &rust-target "1.81.0"
    - &rust-required-nightly "nightly-2024-10-12"
  nixpkgs: &nixpkgs
    - "nix/versions.nix"
  target: &target
    - "x86_64-unknown-linux-gnu"
    - "x86_64-unknown-linux-musl"
  profile: &profile
    - "release"
    - "debug"


runner:
  require: &require
    nixpkgs: *nixpkgs
    llvm: *llvm
    rust:
      - "stable"
      - *rust-target
      - *rust-required-nightly
  inform:
    <<: *require
    llvm:
      - "latest"
    rust:
      - *rust-target
      - "stable"
      - "nightly"

steps:
  profile: *profile
  target: *target
