#!/usr/bin/env bash

set -euo pipefail

# edit the following variables to match your desired rust pins
declare -rx RUST_STABLE_PIN="1.81.0"
declare -rx RUST_MSRV="1.80.0"
declare RUST_NIGHTLY_PIN
RUST_NIGHTLY_PIN="nightly-$(date --utc --iso-8601=date)"
declare -rx RUST_NIGHTLY_PIN

# the rest should be automatically detected
declare RUST_STABLE_LLVM RUST_MSRV_LLVM RUST_NIGHTLY_LLVM
RUST_STABLE_LLVM="$(rustc "+$RUST_STABLE_PIN" -vV | grep 'LLVM version:' | awk '{print $NF}' | sed 's/\([0-9]\+\)\.[0-9]\+\.[0-9]\+/\1/')"
RUST_MSRV_LLVM="$(rustc "+${RUST_MSRV}" -vV | grep 'LLVM version:' | awk '{print $NF}' | sed 's/\([0-9]\+\)\.[0-9]\+\.[0-9]\+/\1/')"
RUST_NIGHTLY_LLVM="$(rustc "+$RUST_NIGHTLY_PIN" -vV | grep 'LLVM version:' | awk '{print $NF}' | sed 's/\([0-9]\+\)\.[0-9]\+\.[0-9]\+/\1/')"
declare -rx RUST_STABLE_LLVM RUST_MSRV_LLVM RUST_NIGHTLY_LLVM

declare -rx WARNING="WARNING: This file is generated by update-rust-pins.sh script. Do not edit it manually."

envsubst < "./builds.template.yml" > "./builds.yml"
