#!/bin/sh

shutdown() {
  echo "Shutting down FRR on signal..."
  pkill -u frr
  pkill -f watchfrr
  pkill -f frr-agent
  exit 0
}

trap shutdown TERM INT

. /libexec/frr/frrcommon.sh


ip -j -d nexthop show | \
  jq --raw-output '.[] | select(.protocol="zebra").id' | \
  while read -r id; do ip nexthop del id "${id}"; done

# shellcheck disable=SC2046
/libexec/frr/watchfrr $(daemon_list) &

/bin/frr-agent "${@}" &

# shellcheck disable=SC3045
wait -n

exit $?
