name: Build
on: [ push, pull_request ]

jobs:
  build-matrix:
    name: generate build matrix
    runs-on:
      - lab
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Setup jq
        # TODO: this seems jank, find a better way to get jq
        uses: vegardit/gha-setup-jq@v1
      - run: cargo install whyq
      - id: matrix
        run: echo matrix="$(yq -r -c '.matrix' builds.yml)" >> "${GITHUB_OUTPUT}"
  build-on-lab:
    name: build-containers
    needs: build-matrix
    runs-on:
      - lab
    timeout-minutes: 300
    strategy:
      matrix: ${{fromJson(needs.build-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v30
      - name: setup nix cache
        id: nix-package-cache
        uses: actions/cache@v4
        with:
          path: /nix
          key: /nix/llvm/${{ matrix.llvm }}/version/${{ hashFiles(matrix.nixpkgs) }}
      - name: install just
        uses: extractions/setup-just@v2
        with:
          just-version: ${{ matrix.just }}
      - name: login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: install uuid-runtime
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends uuid-runtime
      - run: echo "${{ toJSON(matrix) }}"
      - name: Do it!
        run: just --yes debug=true max_nix_builds=1 llvm=${{matrix.llvm}} ci
