name: test suite
on: [ push, pull_request ]

jobs:
  build:
    name: build-container
    runs-on: [lab]
    timeout-minutes: 180
    strategy:
      max-parallel: 4
      matrix:
        profile:
          - debug
          - release
        llvm_version:
          - 18
          - 19
    steps:
      - uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v27
      - name: setup nix cache
        id: nix-package-cache
        uses: actions/cache@v4
        with:
          path: /nix
          key: nix-chache-${{ runner.os }}-${{ matrix.profile }}-llvm${{ matrix.llvm_version }}-${{ hashFiles('./nix/versions.nix') }}
      - name: install just
        uses: extractions/setup-just@v2
      - name: login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build ${{ matrix.profile }} container on llvm "${{ matrix.llvm_version }}"
        run: just build-container ${{ matrix.profile }} "${{ matrix.llvm_version }}"
      - name: push ${{ matrix.profile }} container
        run: just push-container ${{ matrix.profile }} "${{ matrix.llvm_version }}"
      - name: clean up nix
        run: |
          nix-env --delete-generations old
          nix-store --gc
