name: test suite
on: [ push, pull_request ]

jobs:
  build:
    name: build-container
    runs-on: [lab]
    timeout-minutes: 2000
    strategy:
      matrix:
        profile:
          - debug
          # - release
    steps:
      - uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v27
        with:
          # Update when you re-run ./update-version-pinning.sh
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/eabc38219184cc3e04a974fe31857d8e0eac098d.tar.gz
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup nix cache
        id: nix-package-cache
        uses: actions/cache@v4
        with:
          path: /nix
          key: nix-chache-${{ runner.os }}-${{ matrix.profile }}-${{ hashFiles('./nix/versions.nix') }}
      - name: install just
        uses: extractions/setup-just@v2
      - name: login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build ${{ matrix.profile }} container
        run: |
          just build-container ${{ matrix.profile }} || true
      # - name: push ${{ matrix.profile }} container
      #   run: just push-container ${{ matrix.profile }}
