name: test suite
on: [ push, pull_request ]

jobs:
  build-on-lab:
    name: build-containers
    runs-on:
      - lab
    timeout-minutes: 180
    strategy:
      matrix:
        llvm:
          - 19
        just:
          - 1.36.0
        nixpkgs:
          - ${{ hashFiles('./nix/versions.nix') }}
    steps:
      - uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v27
      - name: setup nix cache
        id: nix-package-cache
        uses: actions/cache@v4
        with:
          path: /nix
          key: /nix/llvm/${{ matrix.llvm }}/version/${{ matrix.nixpkgs }}
      - name: install just
        uses: extractions/setup-just@v2
        with:
          just-version: ${{ matrix.just }}
      - name: login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build containers
        run: just llvm="${{matrix.llvm}}" build
      - name: push containers
        run: just llvm="${{matrix.llvm}}" push
      - name: clean up nix to make cache faster
        run: |
          nix-env --delete-generations old
          nix-store --gc
