name: test suite
on: [ push, pull_request ]
defaults:
  run:
    shell: bash -euxo pipefail -c

jobs:
  build-on-lab:
    name: build-containers
    runs-on:
      - lab
    timeout-minutes: 180
    strategy:
      matrix:
        just:
          - 1.36.0
        nixpkgs:
          - "./nix/versions.nix"
        llvm:
          - "18"
          - "19"
    steps:
      - uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v27
      - name: setup nix cache
        id: nix-package-cache
        uses: actions/cache@v4
        with:
          path: /nix
          key: /nix/llvm/${{ matrix.llvm }}/version/${{ hashFiles(matrix.nixpkgs) }}
      - name: install just
        uses: extractions/setup-just@v2
        with:
          just-version: ${{ matrix.just }}
      - name: login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: just --yes debug=true max_nix_builds=1 llvm=${{matrix.llvm}} ci
