# The primary point of this workflow is to ensure that the developer experience is good.
# We take a very vanilla ubuntu image, install all necessary dependencies via "normal" means,
# and then run the build and test steps as described in the README.md file.

# The artifacts produced by these builds are not intended to be used for anything other than
# ensuring that the developer experience is good.

# Production artifacts are produced in a sterile environment (in another CI workflow).

name: "bump"
on:
  workflow_dispatch:
    inputs:
      branch:
        type: "string"
        default: "main"
        description: "which branch to bump"
        required: true
  schedule:
    - cron: "3 10 * * *"
  push:
    branches:
      - "main"

permissions:
  contents: "write"
  pull-requests: "write"
  id-token: "write"
jobs:
  bump:
    runs-on:
      - "lab"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          ref: "${{ github.event.inputs.branch || 'main' }}"
      - uses: "dtolnay/rust-toolchain@stable"
      - uses: "cargo-bins/cargo-binstall@main"
      - run: "cargo binstall --no-confirm just"
      - name: "install nix"
        uses: "cachix/install-nix-action@v30"
      - run: "./scripts/update-version-pinning.sh"
      - name: "Create Pull Request"
        uses: "peter-evans/create-pull-request@v7"
        with:
          branch: "bump/${{ github.event.inputs.branch || 'main' }}"
          title: "bump/${{ github.event.inputs.branch || 'main' }}"
          labels: |
            automated
            dependencies
          sign-commits: "true"
