# The primary point of this workflow is to ensure that the developer experience is good.
# We take a very vanilla ubuntu image, install all necessary dependencies via "normal" means,
# and then run the build and test steps as described in the README.md file.

# The artifacts produced by these builds are not intended to be used for anything other than
# ensuring that the developer experience is good.

# Production artifacts are produced in a sterile environment (in another CI workflow).

name: bump/versions
on:
  workflow_dispatch:
  schedule:
    - cron: "3 10 * * *"

permissions:
  contents: "write"
  pull-requests: "write"
  id-token: "write"
jobs:
  update:
    runs-on:
      - "lab"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - uses: "dtolnay/rust-toolchain@stable"
      - uses: "cargo-bins/cargo-binstall@main"
      - run: "cargo binstall --no-confirm just"
      - name: "install nix"
        uses: "cachix/install-nix-action@v30"
      - run: "./scripts/update-version-pinning.sh"
      - name: "Create Pull Request"
        uses: "peter-evans/create-pull-request@v7"
        with:
          branch: "bump/versions"
          title: "update version pinning"
          labels: |
            automated
            dependencies
            bump/versions
          signoff: "true"
          commit-message: "bump/versions"
          sign-commits: "true"
          body: "update version pinning"
