name: check out test matrix generation
on: [ push, pull_request ]
env:
  max_parallel: 4

jobs:
  test-matrix:
    name: generate test matrix
    runs-on: ubuntu-latest
    outputs:
      require: ${{ steps.require.outputs.matrix }}
      inform: ${{ steps.inform.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Setup jq
        # TODO: this seems jank, find a better way to get jq
        uses: vegardit/gha-setup-jq@v1
      - run: cargo install whyq
      - name: install just
        uses: extractions/setup-just@v2
      - id: require
        run: just generate-test-matrix require >> "${GITHUB_OUTPUT}"
      - id: inform
        run: just generate-test-matrix inform >> "${GITHUB_OUTPUT}"
  require:
    runs-on: ubuntu-latest
    needs: test-matrix
    strategy:
      max-parallel: ${{ env.max_parallel }}
      fail-fast: false
      matrix: ${{fromJson(needs.test-matrix.outputs.require)}}
    steps:
      - run: echo "matrix=${{ toJson(matrix) }}"
  inform:
    runs-on: ubuntu-latest
    needs: test-matrix
    strategy:
      max-parallel: ${{ env.max_parallel }}
      fail-fast: false
      matrix: ${{fromJson(needs.test-matrix.outputs.inform)}}
    steps:
      - run: echo "matrix=${{ toJson(matrix) }}"
