name: check out test matrix generation
on: [ push, pull_request ]
env:
  default_llvm_version: 19
  default_just_version: 1.36.0
  rust_msrv_pin_version: 1.80.1
  rust_stable_pin_version: 1.81.0
  rust_beta_pin_version: 1.82.0-beta.5
  rust_nightly_pin_version: nightly-2024-10-12

jobs:
  gen-matrix:
    name: generate test matrix
    runs-on: ubuntu-latest
    outputs:
      require: ${{ steps.require.outputs.require }}
      inform: ${{ steps.inform.outputs.inform }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Setup jq
        # TODO: this seems jank, find a better way to get jq
        uses: vegardit/gha-setup-jq@v1
      - run: cargo install whyq
      - name: install just
        uses: extractions/setup-just@v2
#      - id: matrix
#        run: just generate-test-matrix require >> >> "${GITHUB_OUTPUT}"
      - id: require
        run: yq -c -r '.matrix.require | "require=" + (.|tostring)' ./environments.yml | tee -a "$GITHUB_OUTPUT"
      - id: inform
        run: yq -c -r '.matrix.inform | "inform=" + (.|tostring)' ./environments.yml | tee -a "$GITHUB_OUTPUT"
#      - id: requirement-matrix
#        run: yq -c -r '.matrix.require | "matrix=" + (.|tostring)' ./environments.yml | tee -a "${GITHUB_OUTPUT}"
  require-matrix:
    runs-on: ubuntu-latest
    needs: gen-matrix
    strategy:
      matrix: ${{fromJson(needs.gen-matrix.outputs.require)}}
    steps:
      - run: echo "required=${{ matrix.required }}"
      - run: echo "nixpkgs=${{ matrix.nixpkgs }}"
      - run: echo "llvm=${{ matrix.llvm }}"
      - run: echo "rust=${{ matrix.rust }}"
      - run: echo "just=${{ matrix.just }}"
  inform-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.gen-matrix.outputs.inform)}}
    steps:
      - run: echo "required=${{ matrix.required }}"
      - run: echo "nixpkgs=${{ matrix.nixpkgs }}"
      - run: echo "llvm=${{ matrix.llvm }}"
      - run: echo "rust=${{ matrix.rust }}"
      - run: echo "just=${{ matrix.just }}"
