# Automatically open a Pull Request in dataplane repository on dpdk-sys updates

name: "update-dp.yml"

on:
  push:
    # Update the dataplane repository each time we push to 'main'. In the
    # future, we may want a more formal process with updates for tags only, but
    # for now we sync on all changes.
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: "boolean"
        description: "Run with tmate enabled"
        required: false
        default: false

concurrency:
  group: "${{ github.workflow }}:${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: "read"
  packages: "read"
  id-token: "write"

jobs:
  bump-dp:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          # Install 'envsubst', used in bump.sh
          sudo apt-get install --yes --no-install-recommends gettext

      - name: "Checkout dataplane repository"
        uses: "actions/checkout@v4"
        with:
          repository: "githedgehog/dataplane"

      - name: "Bump dpdk-sys reference"
        run: |
          ./scripts/bump.sh

      - name: "Generate GitHub App token for the dataplane repository"
        id: "app-token"
        uses: "actions/create-github-app-token@v1"
        with:
          app-id: "${{ secrets.DP_APP_ID }}"
          private-key: "${{ secrets.DP_PRIVATE_KEY }}"
          repositories: "dataplane"

      - name: "Create Pull Request in dataplane repository"
        uses: "peter-evans/create-pull-request@v7"
        with:
          token: "${{ steps.app-token.outputs.token }}"
          branch: "bump/dpdk-sys"
          title: "bump(dpdk-sys): new-version"
          labels: |
            automated
            dependencies
          signoff: "true"
          commit-message: "bump(dpdk-sys): automated bump of dpdk-sys"
          sign-commits: "true"
          body: |
            Automated bump from dpdk-sys,
            triggered by push to 'main' in source repository.

            Commit: ${{ github.sha }}

      - name: "Setup tmate session for debug"
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        uses: "mxschmitt/action-tmate@v3"
        timeout-minutes: 60
        with:
          limit-access-to-actor: true
